[project]
name = "5-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aio-pika==9.4.1",
    "aiosqlite==0.20.0",
    "asyncpg>=0.31.0",
    "boto3>=1.43.6",
    "di>=0.79.2",
    "diator==0.1.2",
    "fastapi==0.111.0",
    "pydantic==2.7.1",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.9",
    "uvicorn==0.30.1",
]
